server:
  port: 8080
spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  application:
    name: /abc
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fzp?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
  redis:
    host: 1.116.137.239
    password:
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  rabbitmq:
    host: amqp-n5e4nvbmomed.rabbitmq.ap-gz.public.tencenttdmq.com
    port: 5672
    username: zjff
    password: eyJrZXlJZCI6ImFtcXAtbjVlNG52Ym1vbWVkIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJhbXFwLW41ZTRudmJtb21lZF96amZmIn0.btwWV9q6qh2DKbcf9m565QmKys17TeCmh3VFXcxiECE
    template:
      exchange: zjff
      default-receive-queue: zjff
    virtual-host: /
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.f002.f002.Entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-column-label: true
    use-generated-keys: true
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      example:
        mapper: debug
#logging.level.org.springframework.boot.autoconfigure: error

